# Generated by Django 3.2.8 on 2021-10-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquore_store_app', '0002_auto_20211030_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
