# Generated by Django 3.2.8 on 2021-10-31 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquore_store_app', '0005_auto_20211031_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cliente',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='cliente',
            new_name='user',
        ),
    ]
